### ISSUE TITLE
[Feature] Hide/show Social Floating Button on certain page

### ISSUE THREAD

**Issue by aron-bordin** [aron-bordin/neo-hpstr-jekyll-theme#2]

**Comment by aleksandar-todorovic** [comment]
Just trying to switch from `hpstr` to `neo-hpstr` and this is the first issue I found (as in, I'd love to get rid of that Social Floating Button thing completely).

Any progress on this?

**Comment by aron-bordin** [comment]
Hi,
this is quite simple, I'll add it tonight.

**Comment by aleksandar-todorovic** [comment]
Hi,

Please ping me here once you do.

**Comment by aron-bordin** [comment]
@aleksandar-todorovic just added a `float_share` variable in `_config.yml`. You can set it to false to disable the sharing button now.

**Comment by aleksandar-todorovic** [comment]
Thanks! Looking forward to switching to your theme.
