### ISSUE TITLE
How can I remove some of the floating social sharing buttons? 

### ISSUE THREAD

**Issue by valasatava** [aron-bordin/neo-hpstr-jekyll-theme#27]
I'd like to keep just some of the options in a floating social sharing bar. What is the best way to do it?

**Comment by aron-bordin** [comment]
Hi @valasatava 
You need to edit this line: https://github.com/aron-bordin/neo-hpstr-jekyll-theme/blob/master/assets/js/_main.js#L93

You can read more about it here: https://github.com/ozdemirburak/jquery-floating-social-share

After editing the line, install the required tools with `npm install` and compile the js with `grunt` commands.

Let me know if you need any help :)
