### ISSUE TITLE
Creating non-blog page from markdown

### ISSUE THREAD

**Issue by apryor6** [aron-bordin/neo-hpstr-jekyll-theme#31]
I'm building a portfolio with this theme that consists of projects that I write as blog posts in markdown. That works great, but I also want to build other permanent pages, like a publications page, with the same theme. How can I write a page in markdown and have Jekyll convert it to HTML in the same way as a blog post, but without including it as such?

**Comment by aron-bordin** [comment]
Instead of creating a post, you should create a new page. Just create a folder with the url of your page and inside it, a file named ``ìndex.md``.

For example, to create a page at ``<your-site-url>/mypage`` creates the file ``mypage/index.md`` and adds the page content.

(Take a look in the about page here: https://github.com/aron-bordin/neo-hpstr-jekyll-theme/blob/master/about/index.md)

**Comment by apryor6** [comment]
Sorry, where specifically do I make this folder? I tried making it in the
same folder as _config.yml but get a 404 upon using my link to the new page
(it also doesn't have an .html associated in the generate _site)

---------------------------------------------------
Alan (AJ) Pryor
Ph.D. Candidate
UCLA Coherent Imaging Group
University of California, Los Angeles
Department of Physics and Astronomy
(478-232-2486)
---------------------------------------------------

**Comment by aron-bordin** [comment]
The demo source code has the about page (http://aronbordin.com/neo-hpstr-jekyll-theme/about/), check the ``about`` folder in the root directory, and inside it you have the ``index.md``. Just create the new folder in the root of the site source, and then add the name of the folder to the url. (See, the about folder created the ``/about/`` page.

**Comment by apryor6** [comment]
I got it working, thanks very much. It's a great theme.

---------------------------------------------------
Alan (AJ) Pryor
Ph.D. Candidate
UCLA Coherent Imaging Group
University of California, Los Angeles
Department of Physics and Astronomy
(478-232-2486)
---------------------------------------------------
