### ISSUE TITLE
Problem using highlight

### ISSUE THREAD

**Issue by JeanCCV** [aron-bordin/neo-hpstr-jekyll-theme#34]
I try to use `` `example of highlight ` `` for highlight something but

**The output html is:**

```
<code class="highlighter-rouge"><table style="border-spacing: 0"><tbody><tr><td class="gutter gl" style="text-align: right"><pre class="lineno">1</pre></td><td class="code"><pre>example of highlight <span class="w">
</span></pre></td></tr></tbody></table>
</code>

```

**When they should be:**

`<code class="highlighter-rouge">example of highlight </code>`

I dont know how to solve this problem, please help.

the url of my test page is https://jeanccv.github.io/neo-hpstr-jekyll-theme/theme-setup/

**Comment by jrfnl** [comment]
AFAICS this is unrelated to the theme, but an issue with the highlighter plugin being used.
