### ISSUE TITLE
tzinfo dependency error

### ISSUE THREAD

**Issue by cakirhal** [aron-bordin/neo-hpstr-jekyll-theme#40]
I installed theme and try running with:

bundle exec jekyll serve --watch

It says:

Configuration file: C:/Users/cakirhal/Desktop/demo/_config.yml
  Dependency Error: Yikes! It looks like you don't have tzinfo or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- tzinfo' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!
jekyll 3.4.0 | Error:  tzinfo

I installed tzinfo, but it didn't solve the problem. After removing below lines from _config.yml solve the problem:

timezone:    Europe/Istanbul
locale:      tr_TR
future:      true

What is the best way to solve this issue?

**Comment by Bodeman** [comment]
Got the same issue. Bump.

**Comment by edwin-huber** [comment]
I run on windows and solved by installing the tzinfo-data gem:

`gem install tzinfo-data`

then adding this to the Gemfile in the root of the site:

```Ruby
gem 'tzinfo-data'
```

This was my source:
https://github.com/tzinfo/tzinfo/wiki/Resolving-TZInfo::DataSourceNotFound-Errors

**Comment by cakirhal** [comment]
It worked. Thanks.

**Comment by wenhaiz** [comment]
deleting the timezone line works,thank you

**Comment by FoxInCloud** [comment]
Worked for me too

**Comment by pimozid** [comment]
worked for me too ,thank you

**Comment by hackersheng** [comment]
thank you

**Comment by debiantano** [comment]
> Ejecuté en Windows y lo resolví instalando la gema tzinfo-data:
> 
> `gem install tzinfo-data`
> 
> luego agregando esto al Gemfile en la raíz del sitio:
> 
> ```ruby
> gema  'tzinfo-data'
> ```
> 
> Esta fue mi fuente:
> https://github.com/tzinfo/tzinfo/wiki/Resolving-TZInfo::DataSourceNotFound-Errors

Muchas gracias en verdad funcionó ya que soy nuevo todavia para estas cosas

**Comment by Vi1234sh12** [comment]
![Screenshot (567)](https://user-images.githubusercontent.com/45570993/109105937-d6d25980-7754-11eb-9181-97280be875ba.png)

![Screenshot (568)](https://user-images.githubusercontent.com/45570993/109105767-95da4500-7754-11eb-911b-6043f1e9a027.png)

Anyone can you help me for solving this error

**Comment by jeromehanan** [comment]
> 
> 
> I run on windows and solved by installing the tzinfo-data gem:
> 
> `gem install tzinfo-data`
> 
> then adding this to the Gemfile in the root of the site:
> 
> ```ruby
> gem 'tzinfo-data'
> ```
> 
> This was my source:
> https://github.com/tzinfo/tzinfo/wiki/Resolving-TZInfo::DataSourceNotFound-Errors

Thanks mate!!

**Comment by barungh** [comment]
> 
> 
> ![Screenshot (567)](https://user-images.githubusercontent.com/45570993/109105937-d6d25980-7754-11eb-9181-97280be875ba.png)
> 
> ![Screenshot (568)](https://user-images.githubusercontent.com/45570993/109105767-95da4500-7754-11eb-911b-6043f1e9a027.png)
> 
> Anyone can you help me for solving this error

You are using Bundler I think,

You need to put ```gem 'tzinfo-data'``` in your Gemfile

**Comment by pajarrahmansyah** [comment]
> > ![Screenshot (567)](https://user-images.githubusercontent.com/45570993/109105937-d6d25980-7754-11eb-9181-97280be875ba.png)
> > ![Screenshot (568)](https://user-images.githubusercontent.com/45570993/109105767-95da4500-7754-11eb-911b-6043f1e9a027.png)
> > Anyone can you help me for solving this error
> 
> You are using Bundler I think,
> 
> You need to put `gem 'tzinfo-data'` in your Gemfile

It works, thanks
