### ISSUE TITLE
Running on Github Pages

### ISSUE THREAD

**Issue by leecalcote** [aron-bordin/neo-hpstr-jekyll-theme#44]
What's the trick to running this theme on Github Pages? I receive this build warning:

"You are attempting to use a Jekyll theme, "neo-hpstr-jekyll-theme", which is not supported by GitHub Pages. "

Repo: https://github.com/leecalcote/gingergeek
Site: http://calcotestudios.com/gingergeek

**Comment by XericZephyr** [comment]
Same question here.

**Comment by nrbrd** [comment]
Hi !
You can just remove the "theme: neo-hpstr-jekyll-theme" line from config

**Comment by leecalcote** [comment]
Thanks, @aron-bordin!
