### ISSUE TITLE
Inline markdown not rendering correctly

### ISSUE THREAD

**Issue by apryor6** [aron-bordin/neo-hpstr-jekyll-theme#51]
I have recently encountered an issue with inline markdown code with backticks failing to render properly. I previously had blog posts that looked correct, but upon adding something new and rerendering the entire site it appears inline code is broken everywhere. Do you observe a similar problem?

**Comment by jrfnl** [comment]
@apryor6 Just wondering: when did you last rerender the site ? and what version of Jekyll et al are you using. Markdown is supported by default using `kramdown`, but there are also some extensions around with slightly different interpretations.
Most notably GH Pages switched to Jekyll 3 in Feb 2016 removing support for the often used `RedCarpet` alternative and that caused quite some trouble for quite a few sites. See https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

**Comment by apryor6** [comment]
This is through my GitHub pages on this account. I did note the recent change and adjusted my configuration file to reflect markdown: kramdown, but that unfortunately did not help.

**Comment by jrfnl** [comment]
The change I mentioned above also included a switch from Pygments to Rouge for the code highlighter, I've seen quite some issues with that as well. Could that be the real reason for your issue ?

This is a draft of an article I intended to publish around that time (but never got round to publishing in the end), might be helpful for you: https://gist.github.com/jrfnl/bc3fa4a92acc67c83717
