### ISSUE TITLE
Implement a read more button 

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [aron-bordin/neo-hpstr-jekyll-theme#57]
How do you implement a read more button? I would like to only show a teaser of the full post at the "home" section (as you did on your blog).

**Comment by nrbrd** [comment]
Check this post, as an example: https://raw.githubusercontent.com/rhesoftsolutions/Blog/gh-pages/_posts/2014-05-21-cordovaphonegap-ebook-reader-for-web-and-mobile-with-epub-js-plugin.markdown

You need to add the ``<!-- more -->`` tag, it will be replaced with the read more button.

**Comment by Sebastian-Nielsen** [comment]
@aron-bordin 
I already tried that for some reason it does not hide the markdown under the `<!-- more -->` tag. As seen on this [screenshot](https://cl.ly/1M0M2e3w0g3M). Although the button works as expected.

I assume you got a file that handles the `<!-- more -->`  tag differently than mine, one that you have not yet commited to the [theme](https://github.com/mmistakes/hpstr-jekyll-theme)..?  
This would explain why the tag does not work as intended on my machine.
